apiVersion: v1
kind: Service
metadata:
  name: ml-inference-k8s
  labels:
    app: ml-inference-k8s
spec:
  type: ClusterIP
  selector:
    app: ml-inference-k8s
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
